server:
  port: ${SERVER_PORT:1005}

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/whitelistedip?useSSL=false&allowPublicKeyRetrieval=true&connectTimeout=20000
    username: ${MYSQL_USERNAME:xxx}
    password: ${MYSQL_PWD:xxx}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: mysql
  application:
    name: whitelist-service
  profiles:
    active: ${ACTIVE_PROFILE:dev}
